name: adpi2 goodbye action
description: A simple action to say goodbye
author: adpi2
branding:
  icon: heart
  color: blue
inputs:
  goodbye-greeting:
    description: Your custom greeting to say goodbye
    required: false
    default: Bye
  receiver:
    description: The receiver of your greeting
    required: false
    default: World
runs:
  using: 'node16'
  main: 'dist/index.js'
